import Link from 'next/link'
import { getReports } from '@/lib/research'

/**
 * Cards linking into /research/[slug]/. Read from web/content/research/*.md at
 * build time via getReports(), which respects the `publish: true` frontmatter
 * gate — a file dropped into the corpus without opting in still cannot ship.
 */
export default function ResearchSection() {
  const reports = getReports()

  return (
    <section id="research" className="section research" aria-labelledby="research-title">
      <header className="section-head">
        <p className="section-kicker">03 · Research</p>
        <h2 id="research-title" className="section-title">
          AI drafts.<span>A human verifies.</span>
        </h2>
        <p className="section-lede">
          Every piece here was generated by a Sapphire agent and then read by a
          person before it published. The corpus is committed to git — a stale
          claim is visibly stale, and the sync script cannot ship a piece that
          did not carry <code>publish: true</code>.
        </p>
      </header>

      <ul className="research-list" aria-label="Published research">
        {reports.map((report, i) => (
          <li key={report.slug} style={{ animationDelay: `${i * 60}ms` }}>
            <Link href={`/research/${report.slug}/`} className="research-card">
              <div className="research-card-head">
                <span className="research-card-meta">
                  {report.date ?? 'undated'} · {report.minutes} min read
                </span>
                {report.tags[0] && (
                  <span className="research-card-tag">#{report.tags[0]}</span>
                )}
              </div>
              <h3>{report.title}</h3>
              {report.description && <p>{report.description}</p>}
              <span className="research-card-cta">Read →</span>
            </Link>
          </li>
        ))}
      </ul>
    </section>
  )
}
